### ISSUE TITLE
cannot update from 5.1.4 to 5.2.0 using rocketchatctl update

### ISSUE THREAD

**Issue by dotty37** [RocketChat/install.sh#70]
### Description:

I have an AWS EC2 instance originally deployed with AMI Marketplace official Rocket image.
Ive alway use rocketchatctl update to update to the latest Rocket.chat.
Im on 5.1.4 and Im trying to update to 5.2.0 and I get:

myip:~$ sudo rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
Current update available for RocketChat server: from 5.1 to 5.2.0.
/usr/local/bin/rocketchatctl: line 1175: run: command not found
mkdir: cannot create directory ‘/opt/nvm’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15916  100 15916    0     0   740k      0 --:--:-- --:--:-- --:--:--  740k
=> nvm is already installed in /opt/nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /root/.bashrc
=> bash_completion source string already in /root/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="/opt/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
v14.19.3 is already installed.
Now using node v14.19.3 (npm v6.14.17)
/opt/nvm/nvm.sh: line 3319: EXIT_CODE: unbound variable

======

### Steps to reproduce:

1. 
2. Terminal
3. 
4. Type rocketchatctl update
5. 

### Expected behavior:

Upgrade to the latest version
### Actual behavior:
Stuck in the old version

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.4
- Operating System: Ubuntu 20.04.5 LTS
- Deployment Method:  AMAZON AMI
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: db version v5.0.9

### Client Setup Information

- Desktop App or Browser Version: NA
- Operating System: NA

### Relevant logs:
Not sure how to get the logs, sorry :-(

**Comment by valentiandrea** [comment]
> Hi!
> 
> You can update the script by running `sudo curl -O $(which rocketchatctl) https://raw.githubusercontent.com/RocketChat/install.sh/master/rocketchatctl`
> 
> Please let me know if the updated script fixes the issue or not.
> 
> Thanks!

Same error also with the updated script

**Comment by dotty37** [comment]
I already reported it doesnt work.
I just see the content of the script scrolling,, not executing,, as when I
just open the file fusing 'cat'

**Comment by debdutdeb** [comment]
Ah sorry I wrote the command wrong 🙈 it's
```
sudo curl -o $(which rocketchatctl) https://raw.githubusercontent.com/RocketChat/install.sh/master/rocketchatctl
```

**Comment by georgemaschke** [comment]
> sudo curl -o "$(which rocketchatctl)" "https://raw.githubusercontent.com/RocketChat/install.sh/master/rocketchatctl"

Running this command did not resolve the issue on my instance of Rocket.Chat. Upon running `rocketchatctl update` I receive the same error mentioned by @dotty37:

Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
Current update available for RocketChat server: from 5.1 to 5.2.0.
v14.19.3 is already installed.
Now using node v14.19.3 (npm v6.14.17)
/opt/nvm/nvm.sh: line 3319: EXIT_CODE: unbound variable

**Comment by debdutdeb** [comment]
Thank everyone, I'll take a look tonight.

**Comment by dotty37** [comment]
I know you are all busy, but I was wondering if there has been any progress on this.
I'm afraid that because this issue is not in the root repository anymore, it has now less visibility and might be forgotten.

**Comment by debdutdeb** [comment]
Hi ! Sorry couldn't work on it last couple days. Just sat down with it 🙂

**Comment by dotty37** [comment]
Maybe we should move this back to the root repository :-( I dont want to bother,, I just want to stay current and not fall behind so much in versions, as this might cause update issues in the future.

**Comment by debdutdeb** [comment]
You all should now be able to update fine :) Idk what's wrong with nvm, but for this update, you should be fine. I'm doing a whole rewrite of the script any way. First update the rocketchatctl script with the aforementioned command and rerun the update command :)

```
sudo curl -o "$(which rocketchatctl)" "https://raw.githubusercontent.com/RocketChat/install.sh/master/rocketchatctl"
```

**Comment by georgemaschke** [comment]
Thank you, @debdutdeb! To confirm, I was able to successfully update to Rocket.Chat 5.2.0 by running:

`rocketchatctl upgrade-rocketchatctl`
`rocketchatctl update`

**Comment by dotty37** [comment]
Im getting "Bad Gateway" and my rocket is down.
Rebooting didnt help.
I ran:
sudo curl -o "$(which rocketchatctl)" "https://raw.githubusercontent.com/RocketChat/install.sh/master/rocketchatctl"
rocketchatctl upgrade-rocketchatctl
rocketchatctl update

On the last command I got this response:
sudo rocketchatctl update
Updates could be risky, you can use the backup option # rocketchatctl backup, to create a backup of the rocketchat database first. Please check that you have enough space in your system to store the backup.
Current update available for RocketChat server: from 5.1 to 5.2.0.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0   2693      0 --:--:-- --:--:-- --:--:--  2693
100  211M  100  211M    0     0   100M      0  0:00:02  0:00:02 --:--:--  107M
/usr/local/bin/rocketchatctl: line 438: npm: command not found
Waiting up to 5 minutes for RocketChat server to be active ... 2
RocketChat server not running. Cancelling


I must have done something wrong, but I dont know what.
:-(

**Comment by debdutdeb** [comment]
Run `source /opt/nvm/nvm.sh` before running the update command.

**Comment by debdutdeb** [comment]
I will try to release the v2 some time next week. Should take care of issues like these.

**Comment by dotty37** [comment]
It is too late for that, now my rocket is not running.
source /opt/nvm/nvm.sh runs without any output, and the update command wont work because rocket is down. :-(

**Comment by dotty37** [comment]
By the way, thanks for the help,, Im just not too good with this.

**Comment by debdutdeb** [comment]
What's the output of `ls /opt`

**Comment by dotty37** [comment]
This is what I have running:

systemctl | grep running
  proc-sys-fs-binfmt_misc.automount                loaded active running   Arbitrary Executable File Formats File System Automount Point                
  acpid.path                                       loaded active running   ACPI Events Check                                                            
  init.scope                                       loaded active running   System and Service Manager                                                   
  session-1.scope                                  loaded active running   Session 1 of user ubuntu                                                     
  session-3.scope                                  loaded active running   Session 3 of user ubuntu                                                     
  accounts-daemon.service                          loaded active running   Accounts Service                                                             
  acpid.service                                    loaded active running   ACPI event daemon                                                            
  atd.service                                      loaded active running   Deferred execution scheduler                                                 
  cron.service                                     loaded active running   Regular background program processing daemon                                 
  dbus.service                                     loaded active running   D-Bus System Message Bus                                                     
  getty@tty1.service                               loaded active running   Getty on tty1                                                                
  ModemManager.service                             loaded active running   Modem Manager                                                                
  multipathd.service                               loaded active running   Device-Mapper Multipath Device Controller                                    
  networkd-dispatcher.service                      loaded active running   Dispatcher daemon for systemd-networkd                                       
  polkit.service                                   loaded active running   Authorization Manager                                                        
  rsyslog.service                                  loaded active running   System Logging Service                                                       
  serial-getty@ttyS0.service                       loaded active running   Serial Getty on ttyS0                                                        
  snap.amazon-ssm-agent.amazon-ssm-agent.service   loaded active running   Service for snap application amazon-ssm-agent.amazon-ssm-agent               
  snapd.service                                    loaded active running   Snap Daemon                                                                  
  ssh.service                                      loaded active running   OpenBSD Secure Shell server                                                  
  systemd-journald.service                         loaded active running   Journal Service                                                              
  systemd-logind.service                           loaded active running   Login Service                                                                
  systemd-networkd.service                         loaded active running   Network Service                                                              
  systemd-resolved.service                         loaded active running   Network Name Resolution                                                      
  systemd-timesyncd.service                        loaded active running   Network Time Synchronization                                                 
  systemd-udevd.service                            loaded active running   udev Kernel Device Manager                                                   
  traefik.service                                  loaded active running   Traefik                                                                      
  udisks2.service                                  loaded active running   Disk Manager                                                                 
  unattended-upgrades.service                      loaded active running   Unattended Upgrades Shutdown                                                 
  user@1000.service                                loaded active running   User Manager for UID 1000                                                    
  acpid.socket                                     loaded active running   ACPID Listen Socket                                                          
  dbus.socket                                      loaded active running   D-Bus System Message Bus Socket                                              
  multipathd.socket                                loaded active running   multipathd control socket                                                    
  snapd.socket                                     loaded active running   Socket activation for snappy daemon                                          
  syslog.socket                                    loaded active running   Syslog Socket                                                                
  systemd-journald-audit.socket                    loaded active running   Journal Audit Socket                                                         
  systemd-journald-dev-log.socket                  loaded active running   Journal Socket (/dev/log)                                                    
  systemd-journald.socket                          loaded active running   Journal Socket                                                               
  systemd-networkd.socket                          loaded active running   Network Service Netlink Socket                                               
  systemd-udevd-control.socket                     loaded active running   udev Control Socket                                                          
  systemd-udevd-kernel.socket                      loaded active running   udev Kernel Socket                                                           
  ua-timer.timer                                   loaded active waiting   Ubuntu Advantage Timer for running repeated jobs

**Comment by dotty37** [comment]
ls /opt
Rocket.Chat  Rocket.Chat.bkup  nvm

**Comment by debdutdeb** [comment]
There should be a directory named `Rocket.Chat.bkp` don't remember the exact suffix. 

You can rename that to just Rocket.Chat with `mv` command. Then run `systemctl restart rocketchat`. That should bring it back up.

**Comment by dotty37** [comment]
Yes,, there is one,, is on the output of ls /opt I pasted above,,, should I first delete the other "Rocket.chat" folder that is right next to it and then mv? or just do like you say?

**Comment by debdutdeb** [comment]
Oh there are two. 
Let's check then why it is failing. `systemctl status rocketchat`

**Comment by dotty37** [comment]
I did: 
sudo mv /opt/Rocket.Chat /opt/Rocket.ChatXX
Then I did:
sudo mv /opt/Rocket.Chat.bkup /opt/Rocket.Chat
Lastly: 
systemctl restart rocketchat
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to restart 'rocketchat.service'.
Authenticating as: Ubuntu (ubuntu)
Password: 
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
Failed to restart rocketchat.service: Access denied
See system logs and 'systemctl status rocketchat.service' for details.

I rebooted the server.

I ran: systemctl status rocketchat

● rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-10-27 12:55:35 UTC; 2s ago
    Process: 915 ExecStart=/opt/nvm/versions/node/v14.19.3/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
   Main PID: 915 (code=exited, status=1/FAILURE)

Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]: Error: Cannot find module '/opt/Rocket.Chat/main.js'
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]:     at internal/main/run_main_module.js:17:47 {
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]:   code: 'MODULE_NOT_FOUND',
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]:   requireStack: []
Oct 27 12:55:35 ip-172-30-4-26 rocketchat[915]: }
Oct 27 12:55:35 ip-172-30-4-26 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 12:55:35 ip-172-30-4-26 systemd[1]: rocketchat.service: Failed with result 'exit-code'.

**Comment by dotty37** [comment]
I googled "Cannot find module '/opt/Rocket.Chat/main.js", some other people had similar issues.
Maybe I messed something up with all the things I did last week trying to solve the upgrade.

This is my command history from last week, I think:
  174  sudo rocketchatctl -h
  175  sudo rocketchatctl update
  176  vi /opt/nvm/nvm.sh 
  177  nvm list
  178  nvm
  179  export NVM_DIR=~/.nvm
  180  . .nvm/nvm.sh
  181  export NVM_DIR=~/.nvm . .nvm/nvm.sh
  182  export NVM_DIR=~/.nvm
  183  . .nvm/nvm.sh
  184  ..nvm/nvm.sh
  185  sudo rocketchatctl update
  186  export NVM_DIR=~/.nvm . .nvm/nvm.sh
  187  export NVM_DIR=~/.nvm
  188  .nvm/nvm.sh
  189  nvm/nvm.sh
  190  sudo find / -name nvm.sh
  191  ./opt/nvm/nvm.sh
  192  ../opt/nvm/nvm.sh
  193  /opt/nvm/nvm.sh
  194  sudo /opt/nvm/nvm.sh
  195  sudo ./opt/nvm/nvm.sh
  196  sudo basj /opt/nvm/nvm.sh
  197  sudo bash /opt/nvm/nvm.sh
  198  sudo rocketchatctl update

Im sure I broke something. :-( 
I was following online posts regarding the rocket.chat update.

**Comment by dotty37** [comment]
I just took a backup of the db with 
sudo rocketchatctl backup and saved the dump on my laptop.

I have an AWS snapshot from the root volume, taken 10 days ago.
Perhaps I can just put that snapshot online, restore the DB from the dump file using mongorestore and see if I can bring my most up-to-date conversations,,
Then I could try the update to 5.2.0 again.

Does that sound ok?

**Comment by debdutdeb** [comment]
Yes, I think that's the quickest way of fixing this :) 

But, don't bring down your existing system though, just in case. Once the other one from the snapshot is up, and the backup is restored and verified, I think is the right time to terminate the current one.

**Comment by dotty37** [comment]
I did,,, took a snapshot from the failed one just in case.
I brought the old snapshot back, and the server was running on 5.1.4.
Then I restored the DB, and got all the recent data.
Then I tried the upgrade again like this:

sudo curl -o "$(which rocketchatctl)" "https://raw.githubusercontent.com/RocketChat/install.sh/master/rocketchatctl"
sudo rocketchatctl upgrade-rocketchatctl
source /opt/nvm/nvm.sh  (didnt work with sudo)
sudo rocketchatctl update


And the rocket server didnt start.

Im here now:
sudo systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-10-27 15:25:40 UTC; 31s ago
    Process: 4562 ExecStart=/opt/nvm/versions/node/v14.19.3/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
   Main PID: 4562 (code=exited, status=1/FAILURE)

Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:     at Module.load (internal/modules/cjs/loader.js:950:32)
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:   code: 'MODULE_NOT_FOUND',
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:   requireStack: [
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:     '/opt/Rocket.Chat/programs/server/runtime.js',
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:     '/opt/Rocket.Chat/main.js'
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]:   ]
Oct 27 15:25:40 ip-172-30-4-26 rocketchat[4562]: }
Oct 27 15:25:40 ip-172-30-4-26 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 15:25:40 ip-172-30-4-26 systemd[1]: rocketchat.service: Failed with result 'exit-code'.

:-(

**Comment by dotty37** [comment]
I just reverted it, and put the snapshop back, and restored my most recent db backup.
Im running on 5.1.4 now. I dont know if I should try the upgrade again.

**Comment by dotty37** [comment]
At the end of the upgrade process I get: 
/usr/local/bin/rocketchatctl: line 438: npm: command not found

Maybe npm or node are broken or their paths are wrong, but I dont know how to repair that.
Do you think your V2 script will take care of that? I might just wait for that.
Unless you have some other suggestion.
I can always go back and forth between my broken snapshot and my working snapshot.
Thanks so much for the help !!!

**Comment by debdutdeb** [comment]
yes v2 will 100% take care of these. And much better at debugging too. 5.1.4 is I think not an old version and still supported. So if you can wait a week or two, definitely will be easier.

**Comment by dotty37** [comment]
> yes v2 will 100% take care of these. And much better at debugging too. 5.1.4 is I think not an old version and is still supported. So if you can wait a week or two, definitely will be easier.

Lets do that.. Thanks a lot.. I guess we can close this issue and mark it as "Resolved" because I dont think my problem is something other people might have. I think I messed up my installation a few weeks ago,, not sure.
I will wait a couple of weeks until you release the new script. 
Thanks a lot for the help.

**Comment by dotty37** [comment]
I havent heard anything about the new script. Im still having the same issue.
I even installed a new server from AWS AMI, and I cannot update that one,, same error.
